### ISSUE TITLE
Uncaught TypeError: this.dispatch is not a function

### ISSUE THREAD

**Issue by beniaminorossini** [jantinnerezo/livewire-range-slider#3]
Hi @jantinnerezo and thx for your work.

Following installations instructions, i get `Uncaught TypeError: this.dispatch is not a function`

It is maybe related with Alpine JS?
I've included it in this way 
```
<livewire:scripts/>
<script src="//unpkg.com/alpinejs" defer></script>
<x-livewire-range-slider::scripts />
```

Any suggestions?

**Comment by jantinnerezo** [comment]
Hello @beniaminorossini 

You are actually already using this one, I still got to create a release this coming weekend and some changes to it.

For your question, can you move alpine above livewire scripts or you can move it to head instead.

**Comment by beniaminorossini** [comment]
Ok, including `<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>` in the `<head>` do the job.
I've followed [https://laravel-livewire.com/docs/2.x/alpine-js](https://laravel-livewire.com/docs/2.x/alpine-js) for a correct Alpine integration.
Maybe it would be useful to link it directly inside doc?

 Thx

**Comment by jantinnerezo** [comment]
Glad it worked!

Yep will do that man I still have to write a better doc for it before release.

Thanks @beniaminorossini
