### ISSUE TITLE
Laravel 9 problem

### ISSUE THREAD

**Issue by mshahrestani** [jantinnerezo/livewire-range-slider#5]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires jantinnerezo/livewire-range-slider ^1.0 -> satisfiable by jantinnerezo/livewire-range-slider[1.0.0].
    - jantinnerezo/livewire-range-slider 1.0.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by jantinnerezo** [comment]
Hi @mshahrestani, I will add Laravel 9 support within this week.

**Comment by sevak88** [comment]
Any news?)

**Comment by MB116** [comment]
Please check my solution in [Bump required versions #7](https://github.com/jantinnerezo/livewire-range-slider/pull/7)

**Comment by ramsha-mt** [comment]
Any updates? @jantinnerezo

**Comment by jantinnerezo** [comment]
Hi guys, sorry for the radio silence been busy this past weeks

I'll take a look today

**Comment by jantinnerezo** [comment]
Here you go release [1.0.1](https://github.com/jantinnerezo/livewire-range-slider/releases/tag/1.0.1)
